services:
  inventory-service-dev:
    build: .
    container_name: inventory-service-dev
    #command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    command: ["./start.sh"]
    ports:
      - 7200:80 #application
      #- 5678:5678 #debugger
    volumes:
      - .:/code
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres-db:5432/postgres"
      
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"