services:
  inventory-service:
    build: .
    container_name: inventory-service
    #command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    command: ["./start.sh"]
    ports:
      - 7200:80 #application
      #- 5678:5678 #debugger
    volumes:
      - .:/code
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"