services:
  inventory-service-dev:
    build: .
    container_name: inventory-service-dev
    command: ["./start.sh"]
    ports:
      - 7200:80 #application
      #- 5678:5678 #debugger
    volumes:
      - .:/code
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      
  postgres-db:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"