from pydantic import BaseModel, Field
from typing import Any, Dict, Optional
from decimal import Decimal
from datetime import datetime

class Interest(BaseModel):
    propertyId: int = Field(None, description="Property ID")
    userId: str = Field(None, description="User ID")
    timestamp: Optional[datetime] = Field(None, description="Timestamp of interest declaration. Autogenerated by backend.")